version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: blacksea
      MONGO_INITDB_ROOT_PASSWORD: blacksea
      MONGO_INITDB_DATABASE: reactiveSpringExample
    volumes:
      - C:/mongodb/db:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8085:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: blacksea
      ME_CONFIG_MONGODB_ADMINPASSWORD: blacksea